name: Deploy UI to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    name: Build static UI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: yarn

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies (Yarn)
        run: yarn install --frozen-lockfile

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Determine base path for Pages
        shell: bash
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Build UI (Vite)
        run: |
          yarn build:web --base=/${REPO_NAME}/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/frontend

  deploy:
    name: Deploy to Pages
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
